In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [2]:
df = pd.read_csv('sample_data/BMW-data.csv')
df.head(10)

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
5,5 Series,2017,Middle East,Silver,Diesel,Manual,1.9,171362,42926,1232,Low
6,i8,2022,Europe,White,Diesel,Manual,1.8,196741,55064,7949,High
7,M5,2014,Asia,Black,Diesel,Automatic,1.6,121156,102778,632,Low
8,X3,2016,South America,White,Diesel,Automatic,1.7,48073,116482,8944,High
9,i8,2019,Europe,White,Electric,Manual,3.0,35700,96257,4411,Low

In [3]:
df.columns

Index(['Model', 'Year', 'Region', 'Color', 'Fuel_Type', 'Transmission',
       'Engine_Size_L', 'Mileage_KM', 'Price_USD', 'Sales_Volume',
       'Sales_Classification'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 50000 non-null  object
 1   Year                  50000 non-null  int64
 2   Region                50000 non-null  object
 3   Color                 50000 non-null  object
 4   Fuel_Type             50000 non-null  object
 5   Transmission          50000 non-null  object
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64
 8   Price_USD             50000 non-null  int64
 9   Sales_Volume          50000 non-null  int64
 10  Sales_Classification  50000 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB

In [5]:
df.isnull().sum()

Model                   0
Year                    0
Region                  0
Color                   0
Fuel_Type               0
Transmission            0
Engine_Size_L           0
Mileage_KM              0
Price_USD               0
Sales_Volume            0
Sales_Classification    0
dtype: int64

In [6]:
df.isna().sum()

Model                   0
Year                    0
Region                  0
Color                   0
Fuel_Type               0
Transmission            0
Engine_Size_L           0
Mileage_KM              0
Price_USD               0
Sales_Volume            0
Sales_Classification    0
dtype: int64

In [7]:
df.dtypes

Model                    object
Year                      int64
Region                   object
Color                    object
Fuel_Type                object
Transmission             object
Engine_Size_L           float64
Mileage_KM                int64
Price_USD                 int64
Sales_Volume              int64
Sales_Classification     object
dtype: object

In [8]:
df['revenue'] = df['Price_USD'] * df['Sales_Volume']
df['revenue'].head()

0    819542000
1    271562732
2    792175410
3    246749637
4    153685840
Name: revenue, dtype: int64

In [27]:
df['Model'].value_counts()

Model
7 Series    4666
i3          4618
i8          4606
3 Series    4595
5 Series    4592
X1          4570
X3          4497
X5          4487
M5          4478
X6          4478
M3          4413
Name: count, dtype: int64

In [12]:
df.groupby('Model')['revenue'].sum().sort_values(ascending=True).head(10)

Model
M3          1667504386622
X6          1693423254979
M5          1698467355916
X3          1707951188482
X5          1708653383772
i3          1724197530210
5 Series    1735712423092
X1          1752985285361
i8          1764743448529
3 Series    1768534028214
Name: revenue, dtype: int64

In [17]:
df.groupby('Model')['Mileage_KM'].max().sort_values(ascending=False).head(10)

Model
X3          199996
X5          199995
7 Series    199991
i3          199987
M3          199971
5 Series    199956
i8          199955
X1          199954
X6          199935
3 Series    199900
Name: Mileage_KM, dtype: int64

In [19]:
df.groupby('Model')['Mileage_KM'].min().sort_values(ascending=True).head(10)

Model
i3           3
5 Series    21
7 Series    23
X5          29
3 Series    36
M5          42
X1          43
X6          55
i8          57
X3          58
Name: Mileage_KM, dtype: int64

In [28]:
df.groupby('Model')['Sales_Volume'].sum().sort_values(ascending=False).head(10)

Model
7 Series    23786466
i8          23423891
X1          23406060
3 Series    23281303
i3          23133849
5 Series    23097519
M5          22779688
X3          22745529
X5          22709749
X6          22661986
Name: Sales_Volume, dtype: int64

In [11]:
df.groupby('Year')['revenue'].sum().sort_values(ascending=False).head(10)

Year
2022    1344427738820
2024    1312808115466
2019    1289342744664
2016    1284641854435
2021    1272402559079
2014    1269989867142
2010    1261631480830
2011    1258944308614
2013    1258599026870
2012    1257840248199
Name: revenue, dtype: int64

In [30]:
df.groupby('Year')['Price_USD'].mean().sort_values(ascending=False).head(10)

Year
2016    75543.540862
2018    75455.480781
2021    75399.277580
2011    75293.276388
2019    75194.426002
2023    75194.004660
2017    75173.147416
2010    75072.215916
2020    75057.667083
2024    75025.852933
Name: Price_USD, dtype: float64

In [13]:
df.groupby('Region')['revenue'].sum().sort_values(ascending=False).head(10)

Region
Asia             3250635961348
Europe           3188079573212
North America    3182938635076
Middle East      3167783530851
South America    3113805414620
Africa           3108999419352
Name: revenue, dtype: int64

In [35]:
df.groupby('Region')['revenue'].sum().nlargest(5)

Region
Asia             3250635961348
Europe           3188079573212
North America    3182938635076
Middle East      3167783530851
South America    3113805414620
Name: revenue, dtype: int64

In [23]:
df.groupby('Region')['Sales_Volume'].sum().sort_values(ascending=False).head(10)

Region
Asia             42974277
Europe           42555138
North America    42402629
Middle East      42326620
Africa           41565252
South America    41551818
Name: Sales_Volume, dtype: int64

In [22]:
df.groupby('Fuel_Type')['Price_USD'].mean().sort_values(ascending=False).head(10)

Fuel_Type
Electric    75276.313207
Diesel      75079.809671
Petrol      74990.419841
Hybrid      74797.551746
Name: Price_USD, dtype: float64

In [31]:
df.groupby('Fuel_Type')['Sales_Volume'].sum().sort_values(ascending=False)

Fuel_Type
Hybrid      64532097
Petrol      63324154
Electric    63157665
Diesel      62361818
Name: Sales_Volume, dtype: int64

In [14]:
df['Engine_Size_L'].max()

5.0

In [24]:
df['Transmission'].value_counts()

Transmission
Manual       25154
Automatic    24846
Name: count, dtype: int64

In [32]:
df['Sales_Classification'].value_counts()

Sales_Classification
Low     34754
High    15246
Name: count, dtype: int64

In [33]:
df[['Engine_Size_L','Mileage_KM','Price_USD','Sales_Volume']].corr()

               Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume
Engine_Size_L       1.000000   -0.004906   0.000146     -0.003942
Mileage_KM         -0.004906    1.000000  -0.004238      0.001434
Price_USD           0.000146   -0.004238   1.000000      0.000080
Sales_Volume       -0.003942    0.001434   0.000080      1.000000