In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('sample_data/Blinkit.csv')

In [ ]:
df.head(10)

,transaction_id,product_name,product_category,quantity,unit_price,total_price,customer_name,customer_email,purchase_date,payment_method,City,Order_status
0,1,Garlic Naan Bread,Food - Bakery,61,85.10,747.89,Kirk Kenshole,kkenshole0@ehow.com,7/21/2023,credit card,Hyderabad,refunded
1,2,Sweet Potato Mash,Food - Frozen Foods,94,89.64,941.17,Al Clail,aclail1@vk.com,2/13/2026,Apple Pay,Bangalore,delivered
2,3,Honey Graham Crackers,Food - Snacks,90,42.69,259.84,Karita Boskell,kboskell2@bizjournals.com,8/2/2021,Apple Pay,Lucknow,returned
3,4,Car Windshield Sun Shade,Automotive,66,58.33,407.51,Dacie O'Kennavain,dokennavain3@deviantart.com,7/10/2022,Apple Pay,Bangalore,shipped
4,5,Kitchen Knife Sharpening System,Kitchen,17,51.57,270.23,Von Aicheson,vaicheson4@comcast.net,9/15/2024,credit card,Lucknow,returned
5,6,Outdoor Adventure Backpack,Outdoor,29,9.55,594.94,Courtney Armsden,carmsden5@about.me,1/8/2024,Google Pay,Lucknow,delivered
6,7,Multi-Function Smartphone Holder,Electronics,5,28.92,192.87,Feliks Fischer,ffischer6@java.com,1/14/2025,credit card,Kolkata,cancelled
7,8,Streaming Device,Electronics,26,92.76,519.76,Haven Garrod,hgarrod7@latimes.com,11/26/2022,Apple Pay,Ahmedabad,completed
8,9,Electric Bike,Bicycles,13,42.29,91.14,Taddeusz Bener,tbener8@blog.com,8/14/2020,Cash,Mumbai,cancelled
9,10,Maple Bacon Potato Chips,Food - Snacks,33,88.37,931.05,Ali Skates,askates9@de.vu,10/12/2025,Cash,Jaipur,pending

In [ ]:
df.columns

Index(['transaction_id', 'product_name', 'product_category', 'quantity',
       'unit_price', 'total_price', 'customer_name', 'customer_email',
       'purchase_date', 'payment_method', 'City', 'Order_status'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1000 non-null   int64
 1   product_name      1000 non-null   object
 2   product_category  1000 non-null   object
 3   quantity          1000 non-null   int64
 4   unit_price        1000 non-null   float64
 5   total_price       1000 non-null   float64
 6   customer_name     1000 non-null   object
 7   customer_email    1000 non-null   object
 8   purchase_date     1000 non-null   object
 9   payment_method    1000 non-null   object
 10  City              1000 non-null   object
 11  Order_status      1000 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 93.9+ KB

In [ ]:
df.dtypes

transaction_id        int64
product_name         object
product_category     object
quantity              int64
unit_price          float64
total_price         float64
customer_name        object
customer_email       object
purchase_date        object
payment_method       object
City                 object
Order_status         object
dtype: object

In [ ]:
df.isnull()

,transaction_id,product_name,product_category,quantity,unit_price,total_price,customer_name,customer_email,purchase_date,payment_method,City,Order_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

transaction_id      0
product_name        0
product_category    0
quantity            0
unit_price          0
total_price         0
customer_name       0
customer_email      0
purchase_date       0
payment_method      0
City                0
Order_status        0
dtype: int64

In [ ]:
df.isna().sum()

transaction_id      0
product_name        0
product_category    0
quantity            0
unit_price          0
total_price         0
customer_name       0
customer_email      0
purchase_date       0
payment_method      0
City                0
Order_status        0
dtype: int64

In [ ]:
df['transaction_id'].nunique()

1000

In [ ]:
df['total_price'].sum()

np.float64(516681.30000000005)

In [ ]:
df['total_price'].describe()

count    1000.000000
mean      516.681300
std       287.100866
min         1.070000
25%       270.177500
50%       528.480000
75%       772.807500
max       999.430000
Name: total_price, dtype: float64

In [ ]:
df.nlargest(1, 'total_price')

,transaction_id,product_name,product_category,quantity,unit_price,total_price,customer_name,customer_email,purchase_date,payment_method,City,Order_status
748,749,Black Bean Salsa,Food - Snacks,2,25.35,999.43,Corella Waddilow,cwaddilowks@geocities.com,5/9/2022,PayPal,Ahmedabad,shipped

In [ ]:
df.groupby('product_name')['quantity'].sum().sort_values(ascending=False).head(10)

product_name
Fruit & Nut Trail Mix         248
Pineapple Coconut Yogurt      242
Adjustable Bar Stools         236
Colorful Post-It Notes Set    228
Home Karaoke System           223
Pet Grooming Scissors         198
Garden Vegetable Chips        197
Chili Lime Corn Chips         196
Heavy-Duty Utility Tote       192
Outdoor Adventure Backpack    191
Name: quantity, dtype: int64

In [ ]:
df.groupby('product_category')['total_price'].sum().sort_values(ascending=False).head(10)

product_category
Kitchen              44639.78
Food - Snacks        35405.55
Food - Condiments    29478.84
Home                 27629.19
Outdoor              23366.43
Pets                 20201.55
Fitness              16857.75
Accessories          13851.26
Electronics          13431.52
Food - Bakery        12097.86
Name: total_price, dtype: float64

In [ ]:
df.groupby('product_name')['quantity'].sum().sort_values(ascending=False)

product_name
Fruit & Nut Trail Mix         248
Pineapple Coconut Yogurt      242
Adjustable Bar Stools         236
Colorful Post-It Notes Set    228
Home Karaoke System           223
                             ...
Black Bean Salsa                2
Yoga Mat                        1
Infrared Thermometer            1
Ginger Snaps                    1
Fresh Lemons                    1
Name: quantity, Length: 770, dtype: int64

In [ ]:
df.groupby('product_category')['total_price'].sum().sort_values(ascending=False).head()

product_category
Kitchen              44639.78
Food - Snacks        35405.55
Food - Condiments    29478.84
Home                 27629.19
Outdoor              23366.43
Name: total_price, dtype: float64

In [ ]:
df.groupby('customer_name')['total_price'].sum().sort_values(ascending=False).head()

customer_name
Corella Waddilow      999.43
Jeni Smowton          998.81
Hobie Sigge           998.32
Hyacinthie Chasmor    997.60
Darrel Clemenza       994.85
Name: total_price, dtype: float64

In [ ]:
(df['customer_name'].value_counts() > 1)

customer_name
Chas Lashley         False
Kirk Kenshole        False
Al Clail             False
Karita Boskell       False
Dacie O'Kennavain    False
                     ...
Worthy Tournay       False
Ellwood Tunkin       False
Paulo Ventris        False
Ali Skates           False
Taddeusz Bener       False
Name: count, Length: 1000, dtype: bool

In [ ]:
df['customer_name'].unique().sum()

"Kirk KensholeAl ClailKarita BoskellDacie O'KennavainVon AichesonCourtney ArmsdenFeliks FischerHaven GarrodTaddeusz BenerAli SkatesPaulo VentrisEllwood TunkinWorthy TournayEmlynne DavidovMoira SlaneAnnabela DrewetCatherina LambolBobbye ParkMarcia LaffinRollins MagnusValentin HuckfieldMaritsa ArnizTallou SanfordCherise MacChaellTonnie CaterObadias CurteisJoleen SplevinCamille HarcombeBrigit FleuryBruce WestleyCarroll LarterMarsh LohdeTerri CapponerChucho WheelbandArlin SherwynTravus PritchittReba ToplisNatala MacKissackGeorges HeatheringtonHenrik McLoughlinBasilius GilesChlo CowenSuzie BrownseyHarlen JoplingMaire CornilVivian TolworthArlin SponDion PostlesAllyson ApsManfred BussenAlysia ShafeJay ExtanceNathan DubockHarrison CristofaniniSarge YandellJuliette De PaepeDdene GreschikJolyn BernaciakBlinnie McMychemAgnella MacDiarmondEmyle RenboldRobena GaishArnold BreezeJerri BalchArielle GainfortGwen HurcombeTamara ThodyHildegarde VardieLarissa DollinKaterine LuttgerAngelica FarnabyIris BundeyGerrard MerrettBrandais DaringtonNanci ReicherzGian KlimekAlard JanowskiOrtensia MeiklejohnWenda LivermoreEydie DallanderGuinna CreekTiphani BellissAldin GummowBank BodleyAndras BrackenburyPeria SimaPetrina NyssensMiguel McCaddenMichael KindellArchie BertwistleMack CradocRingo Mc KellenAdrianna De MarchiKattie MatyuginMartainn WixDev WelfairCharla McClounanDeena RiderPatten GyvesAddy AllcoatAilbert PyrahDesdemona BrunrothMikel WestbrookLowe ImisonMarigold RemmerCullin KahaneCharil KingzethDedie MinihanePhillis BroadeyBert GummeJoletta MaymanMallory IanizziMeier BerkelyLydie AntatMaggee FumagalliStanwood VauterParry KyngdonWarden ToplisDre BaroschDante IlievePeyton IacofoBordie SilvertonRichy PhantElise EpiscopiDemetra SchouthedeOriana ChazelleMaribeth WhapplesGerome MumbyVidovic PaliaKati VilleMickie RaymanHalsy DowsonLucina SoeiroGay RonnayKessiah HallowesIgnace DaidArlin SextenCristiano BleasdaleIsador FoulcherGerty LeadstoneCooper PietersenCarce ElcockRosaleen VerrierDonnell LefleyChrystal StanhopeAndreas GaitungTess AlbersPaloma BurgwynCosta DrieuBenjie RollingWard ReadeNadya MelsonNovelia DalgardnoNoland RandalesEtheline ArchbouldBurty OldnallDebra KidsleyMahmud MatteuzziShea MacknishCarie CliveWestley De BruinZaneta OrrillAnne BowlandPaolo ComfordFlo DefrainMonty ReveyQuint SimaoZara OfferCullin ChristensenArmin JadczakSindee TemplmanHuey SarfatDulcia LyonTommy AmbrogiottiWilli GriffittCornelle d' EyeNoby DafterAlanah PawlynLorene HinchshawMordecai ClacksonGladys McCaughrenNadine GianuzziMadelyn MeoAlvira ErrickerMasha PriscottHedvig SeppeyEstell ElmhirstMyer WardropJoanie ConwayMac ManuaudPennie NecrewsGillian JacobbeRivalee AcklandsPhineas HarlowLena Campbell-DunlopDiann NutmanNorthrup BurboroughWinnifred ConroyElberta ImminsCordell StarlingPavlov GillfordOsborn WalrondPanchito TubbyMoise BubearRaddie BrosnanDoti SiddellUlrich RandalstonBethany PeregrineRod CrummieJavier ViggersMaurits MompessonMariette BaseggioLlewellyn BuzinJuliana BrazierMax LycettShayna McAughtryJeniece CleetonEddie RosenkrantzMace PenticootPerla PurkessNoland McPaikeSusanna LindGav SybeGunar ReightleyCammy MuldownieWilow HutleyBerte ViciosoRhona KleinMaximilianus CanaanLaureen DawburyDodi MitchelmoreMargret McDarmidMaisey CheeldAntonetta FowlestonePackston PrattLeela MulqueenHulda TribeTessie BoogMadella GriffeyLeeanne VahlAveline DauneyCourtenay MiskenMahmud BaldazziMerrill StickelsTris ArrighiniYolanda TabourJerrilee CowlinAdelind TreffryHayward DonwellIdell StearneMerrick TripletJustinn WatlingFerdy GumbleyMariya OrvissKarlene WorkErhart HanniganShaw SanbrokeMargi FrodsamChev RonnayNathanial WibrewJerrylee AppleFaunie MadeleySheryl HebblewhiteRosamund NatonFree LinningVinnie BuzineDyanna ScrowtonHarp GoldthorpeTildi BrabenderRustin MerritonFidela BlaisdaleCristin AtterDilan SeemanEarly CastagnassoValery GarvieWeber RetterEvangelin DmisekSim FranktonDanell BrackpoolDante MallindineDebera InoldMercedes ClaireLucho LeEstutNatale TomaszekAviva ScanderetWindy FineFrieda SynkeRodney JoyceDoralia BosmaTilly AyscoughBetti HusherShelley HeelVina HallgateLothario AudissNerty StenyngPearl KlemencicWeidar JillardAland DerwinBarclay GiacomiPeterus SkellyGuss BaignardSloane JarayLian D'AlescoCourtney PetranHam CunninghamFidelity BampfordTeodor LawrenzDorris CovelyParke GledhallHoebart StilleTracy StinsonDonnie ArensonAmandy De BruijnHaze GiacoboniFayette ForsonFree NeseyBrigid GodartTobey AstupenasParker YellowleeVivyan VasilchenkoNetti FineCorilla RehorekZebulen BjerkanStormy BourgourMorten KirsteinCorrie RosenboimRay WinkworthKaile SparroweClevey DallicottZacharias QuantrellOlga FeekSheri FinchamTremayne SargersonChrystel PratePhyllys BakewellMajor TwelveTome BeebleVirgie KrinksCesare Di GiacomettinoMartica TrinerRegine MossVite McPartlingRafael FrekeAsia SanthouseTine CasonMeggy CrooseSherline BentoteAmandie CammidgeGene RedsullMikey MormanIago RiccioppoElsie BarthrupDietrich HeenanLynn DouganKrishnah MaithHector SilverBrandy NicolLaina BassillCrysta HaxbyShermy HallockCordy SammonKathrine TunbridgeGlenine SarfassIris MeritonAlvie MaudsleyLoy ArringtonBetsey SeacroftLynnett GershomNannette AuberyGlenine PesticcioSherman BinnesGil PaoliniElinore CrossfieldKermy GurdenTerrell SalackNester TunniclisseErin ZukermanTrudy McErlaineAlmeda HallfordStefanie JosskowitzJillana SkewesCory SeggesJesselyn ParffreyAgretha HealyXaviera OusleyTuesday ManionLorenza FollinMerrill RackamShelli EdonGill SydeDrugi SollnerGrethel GorryNoelle AllakerTaber SalomonKrissy KelingeKetty HaisellGarry CorbetPincus HayhurstCrystie FoukxLeonardo WillgossNolan GoddmanWittie EllingfordAugusto GearKassey GreenwoodHailee CrowsonCarlynne CoitSheridan AxtonHenry StabbinsZia MatejicEtan DobbleBeatrice FouldesZechariah DodsClayton AttackWinthrop CurraghPadget HubnerFabe JoesburyChase SennettTresa NovillEarle BilliardWillem RoyseFidela TreverCalv YudeNanine SparhawkBridie CrannArluene Mc FaulCaye WaadenburgJoachim CorriganDrucy UssherTiffi RubinowCarlita LemmStuart CordovaGerianna DanzeyMyrtice LahiveJaimie HanlinKilian BourAl WrankmoreTarrah GrumbridgeEv SinkingsElicia PooneGustaf KinneirCecil EthertonJoane LourensAntonia BosmanNikolos RichieEmory BortolussiDemeter SzimoniPrissie TortoiseBecca McGahernIsac MicheauGina HeazelFlinn PoulstonMia TrengroveMarty MordantiElihu YearbyRuperto KeldPatrica TakosDarrin BrandtsColline NalderTamas MurkittDonni CheshireJanna ChasmarTanhya MatveikoCullan StroyanRicki WhitesideFreddie RuckhardVergil GatesDyanne HargravesVince JeenesAdelbert AllisonCecilius JodkowskiCherianne KmicickiKaia GiorgeschiGermayne ScholeySherilyn EbbettReynolds BatthewSeumas RufGwenni DuroFreddi GoningBing WorviellPatsy RichardssonLemuel LandellsCarmelita LowtherSalli SiddleAdriane AggettShari StroobandJaquelin PincottGae CarrabotCase DurdleYolanthe MidsonKailey JumpAugie HauckEma GoskerMarci SkuneDorine FreibergKalinda AnwylOliviero HustlerMelisenda EkeErny LeileNolly MilleryLudovika RomaintJustis AldinEmanuele MorlTillie RoakeStesha KnevetTerry FerneleyLambert IsittKath TregenzaRochell PervoeDev GilluleyZachary CassamJoycelin TiesAngus Golden of IrelandVincent LeivesleyKeely ClaricoatesForest HarridgeNickola MacMorlandArdelle AstridgeZaria PerrelleCele CowinSylvester FlatmanAuguste WagenAustina GethenGretta TokleyLynnett OddRinaldo AgutterLindon TollettSandy JakovVernen BaldassiAbagael GosalvezViolante McPeakeKaralee RofeNicol FrielKaterine SymcockClement MatthissonHamlen KrienkeSibel DevasMarilyn MeechanErma KlosgesEmelda GrishakovChristian EnricAline O'DwyerNinnetta MintyJarrid GilbrideDido MardenClerkclaude AucottZarla BauduinGiorgia RichardtDurward GyorgyYancy VartyJayson DermottErmin NunnsIsis FraineAlexander O' DooleyKerrill McNiffCornie BriatMorgana LoudyanDalila JeannardEloisa DoonicanFrederik GornalGlad DaldanAngeline MershBurnard TomaelloChaim SummerleeChevy KyteleyCraggie FluckerAylmar CremenBrandyn ElsburyAubrey RuiltonDianemarie MebiusHagan FlanaghanRose GatecliffMilt VeldenKincaid PettersBetsy DyballFrancklin LimpertzHyacinthie ChasmorLucienne ScothernLucas SlimmingVeronike OldnallAnnadiana FyshLetti PaolacciBianca AvrahmBelva HeinerJanela HainningTrescha BattingMabel LerohanJerri ColbornStanton CaytonElaine FolgerFranklyn EbiSkelly TurpinHamlin PiddingtonYasmeen TandeyTybalt BrunsdenIbrahim CardwellAlta ChellenhamSigmund WharbyLaurent AntonoczykDominica AxtensZita StanneyCharley VakhrushevRhetta BurnettFeodora BanbridgeNita StollhoferRandee De MicoAmelina SuddellAlistair HurburtForbes GhioniFlore DiegoMarian DaverinHieronymus CaustickGretchen WildmanAlfredo JuanicoLion FortonGaspar RubbertTiphany MullingerJermaine DisburyRoxane HearnshawMasha RadnageCaresse OlekMagda CameliArluene BoolsMorgana SwansboroughHadrian BygottZedekiah CandelinCarlie FinesVelma MustoBronson WhetnallWileen KibardSheba NardiLorita BinnerBarthel OgglebieRyley WhaleBryn SquiresCinda DomengeNonie DodimeadTerra PurchesKiley SheddanNestor TreharneThea LegertonGlenine SimonotLydie StennetGretta AlonsoMarcel MatushenkoHedi RiccioGenni LawrenzAnallise GommeryMirabel MaggioreBasilio PrestlandAmelina McRannellGarrek MacConnelKarolina WolfersJo-ann HartrightSioux GurnerTiebout JiranekClary HeamusDorthea DrummerCoralyn De LorenzoLanita WenbanBarde HinrichErtha MichellRedford GallgherOdelia SigsworthGothart BlackdenTalya SoallPippo GyppesAdrianne GrichukhanovShela WhitesonElysee ClardgeHynda AvonClark TeglerZara WilshawFrederico SayJilly WalterDarrel ClemenzaCynde WestellVally BowneMickie EvasonCarolee FauldsEthel RumminNellie McLearyIve ChieseLesya JuggingsImmanuel TaltonSean SeilerRomonda RagglesDewitt TrelevenNicky TurbayneMarrilee BrookzieMora DugdaleAlyse RayntonHenry ScothornPaddie RobezDoro KofaxOlivia AnfossiKarola WilberFrans WethDehlia FabbroBerti DonnellWendy DraiseyViviana KaremanLacie ChucksMelisenda HeysMelvin CackettRobyn GhionHettie AshleeChristiana YakubovicsAurelia Derye-BarrettKitti WixeyYasmeen AshGustave IvanetsIgnace CharlePenn GallemoreSaidee WoolagerRance RatnegeFelic TrasslerOdey EastopeAindrea MaddysonGinevra DorwoodRosemonde AttrillTamiko KimblingHallie PulequeYvon PlaschkeMartica PassmoreUlrich WendenEnrichetta StanelandAlonso ShireBeverly DarbyshireKaspar MeineckGarrott CampSaleem OttamSibelle PragnallDaryn SwynHarrison DivineyLaure GallandAeriela ShowerBald SumersGlori BootherRoarke SpaightLeshia PeelZola LivingstoneKiele PetruszkaHurlee KevernGwenny WorthyLeyla RedholesFelicity BickardikeTristan GosbyAngelica KubeckaCorella WaddilowDannel PryceLynnelle CazinBrooke BogMorris BridellAilee FrancescoccioThorvald WorswickDerk PassionKorney KincaidKris ErrolFrankie RappportMarshall QuaintanceMarve LillecrapToddy VernallYule ToppinAnet BudgeonCristobal BarrassBarris DillowConstancy YankovMarcile ScudamoreJean KuberaGarv BrodeurVelma ManaghAthena DietscheGuillema PhillipDorette HorsburghKarel HoulstonPandora BoasFerrell PoyntzRana McIlvaneyCesare LeonardsJay DaybellHarold VidgeonHugh MilkinsRita CharkhamCurrey WeepersReinaldos GaleaOthilia BerSorcha LimbertEnriqueta KeachSaundra GoodlipLelia HoyerFlorence McKellarFlossy ChaizeHorst CluckieHube BarnsdaleMerell McPolinNicko EdgellCarri O'FairyKatine ErtBlondie RosanderDonnajean PeterMyrtia AbramowitchRochester DelacosteDelbert AllcottNataniel HexhamJamie DinanMimi ChartDela SneddonHortensia ZellickMorris ThistletonLudovico KobUmberto LillegardMahmoud TrenchardWaylon VakhrushinHilarius FilipponeThornton FyfeSax BettonMoyna GiamoBenjamen VillaltaCarola CockingAbe CoselyKimberlyn MacCallumBlane SutheringtonAdria LouderJacinta McCartyMalory BloomanNorine LashmoreBennie RitchElianore DaveyJacinthe CarderoStephana CansdillAlberto DavysLilias HalleyAbbye TurlandCarri GiorgeschiSterne MarriageAugustin FullBrit BarklyErena JedrychowskiGoddard AptedSelene GuerroMarina StanlockFrayda HawksbyFlory SimondsWaylan ZannuttiKurtis GomeryBonita GouldJuana VinterFlorrie WalesbySunny MatashkinAlessandra KenninghanLois GuyetAvigdor SkirlingNancee SpeckGaylord JohniganLief PearmainChip SeakPenrod MathenCurran SanperBriny ArdenNananne BlackmuirLeta KillikFederico McPolinTate PiddockeAlida PleatAnita ChazotteAna DrakesLennie TibaltHenrietta OrnelesLucilia BoggersErick PrewettLilith WoodburneBrenden DrewellArchambault MarrionMaible BarmbyGae WastellOlympie CowthartLulu HintzeCharyl SandelsMayne ArterJoy LyvenLanny SoarPercy RathjenDirk RandsStar McCafferkyJehu EverixCayla ArtinstallJulianne GebbSheryl BetoniaTerrill TaverinerOrson O'ShesnanJoell LowdenZarah LinceReuben SquibbsHarri BroadfootReeta BurtenshawDido OganesianDella HovyPerl FoottitAdina CradeyMatthaeus CarpeCami MetherellMelisande BarfittSpense PacquetRahal EverettSigismund SchoffelGayleen OxbroughJana BentingDarby MuschetteCelene FaradayBertrand DunkerlyJim WaghornHasheem GawthorpRuby PeasnoneElsi RidgesBilly GietzBird SkiptonLindy EversonYance HoundesomeMinetta SimounetElwood MilleaMaribelle MashJeni SmowtonTaffy RamelotBarde GainfortKassi PeverellGeorgia EldinVivi PontenPippy GabbatHerb LubertiJonah ScarlettAguste BrazierGilberte JoplingGlenn HectorTheadora ShawcroftHaze WardenKenon LarkingsRosmunda BallachDasha CrowcombeWilie RocksHobie SiggeDarryl CotterillLeona DorbinKinsley DoigeBrigg DoudneyKirsten HollyarMax OxtobyDarbie BegwellLee CarlessEmlyn DranAilsun SmallthwaiteSusana BryanKynthia LiccardoEloise DoullHelen-elizabeth WinskillKaiser ScarrattErv GausonKoralle CramptonSapphira DalesStar HamblingtonCreighton MacNucatorAlexine DupreyRochella DinningtonAaren PogeSilvana SzwandtSophie LebandCarmine TaylderMack WardesworthMaynord InchbaldBrew GornerAstrix BiskupJaime Le BarrDom PlasterFerdie GatteridgeIlise BownDelphinia ArnaldyAlic BickerEdmund CleveleyGodard TinerHaley ClemmowGerladina AchurchBrien BeekeClarisse PautardDee LindemanShirlee LeeuwerinkWhitby StancliffeAnge ArchibaldFaina BraineSidoney GottschalkMallorie O' LoughranDan ChiezeAnnabelle CunliffeFlynn OldingGillie BalstoneLeigh BubearElsinore RoddickBinky BurtZsa zsa Hall-GoughMohandas CoffeltCasi EarlandChas Lashley"

In [ ]:
df.groupby('customer_name')['total_price'].sum().mean()

np.float64(516.6813)

In [ ]:
df.groupby('City')['total_price'].sum().sort_values(ascending=False).head(5)

City
Ahmedabad    64393.98
Lucknow      56182.70
Hyderabad    55674.69
Bangalore    54205.72
Delhi        53116.20
Name: total_price, dtype: float64

In [ ]:
df['City'].value_counts().head(10)

City
Ahmedabad    114
Lucknow      111
Hyderabad    106
Chennai      104
Mumbai       102
Pune         101
Bangalore     98
Delhi         98
Kolkata       83
Jaipur        83
Name: count, dtype: int64

In [ ]:
df.groupby('City')['total_price'].mean()

City
Ahmedabad    564.859474
Bangalore    553.119592
Chennai      453.369135
Delhi        542.002041
Hyderabad    525.232925
Jaipur       495.065060
Kolkata      519.107831
Lucknow      506.150450
Mumbai       485.700196
Pune         517.226238
Name: total_price, dtype: float64

In [ ]:
df['payment_method'].value_counts()

payment_method
Gift card      185
Google Pay     173
credit card    172
Cash           167
PayPal         160
Apple Pay      143
Name: count, dtype: int64

In [ ]:
df.groupby('payment_method')['total_price'].sum()

payment_method
Apple Pay      75145.71
Cash           88331.92
Gift card      93158.42
Google Pay     86913.74
PayPal         82316.46
credit card    90815.05
Name: total_price, dtype: float64

In [ ]:
df['Order_status'].value_counts()

Order_status
completed      111
on hold        108
pending        106
cancelled      104
delivered      102
refunded       101
processing      97
returned        96
shipped         88
backordered     87
Name: count, dtype: int64

In [ ]:
df.groupby('Order_status')['total_price'].sum()

Order_status
backordered    45247.75
cancelled      51596.47
completed      56983.82
delivered      58891.58
on hold        52978.44
pending        55146.67
processing     51067.68
refunded       51226.38
returned       49029.13
shipped        44513.38
Name: total_price, dtype: float64

In [ ]:
(df['Order_status'] == 'cancelled').mean()*100

np.float64(10.4)

In [ ]:
df.groupby('purchase_date')['total_price'].sum().sort_values(ascending=False).head(10)

purchase_date
6/21/2021     2517.34
7/29/2025     2270.98
12/16/2026    2171.76
3/9/2020      2096.84
1/14/2021     2013.47
5/9/2022      1928.74
5/5/2020      1839.03
10/30/2025    1770.73
3/18/2026     1756.94
6/15/2021     1752.01
Name: total_price, dtype: float64

In [ ]:
df.groupby('purchase_date')['total_price'].sum().idxmax()

'6/21/2021'

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])
df.groupby(df['purchase_date'].dt.month)['total_price'].sum()

purchase_date
1     46415.39
2     37854.62
3     46580.52
4     48496.94
5     41001.71
6     40297.68
7     57426.07
8     46484.80
9     39787.10
10    38676.60
11    32113.67
12    41546.20
Name: total_price, dtype: float64